#!/usr/bin/env python3
import rospy
import numpy as np
from time import time
from pathlib import Path
from collections import deque
from rosllm_srvs.srv import LLM, LLMRequest
from std_msgs.msg import Float64MultiArray, String

prompt_template = """
You are a sensor data summarizer. 

The following is a description of the sensor:
{sensor_description}

The average sampling rate is {hz} Hz.

The following is {num_samples} most recent sensor data points, provide a concise summary:
{sensor_data}
"""

class GeneralSensorSummarizerNode:
    def __init__(self):
        rospy.init_node("general_sensor_summarizer_node")
        self.max_history = rospy.get_param("~max_history", 1)
        self.history = deque(maxlen=self.max_history)
        self.sensor_description = Path(rospy.get_param("~sensor_description_path")).read_text()
        rospy.Subscriber("sensor_data", Float64MultiArray, self.sensor_data_callback)
        self.hz = rospy.get_param("~hz", 1.0)
        self.pub = rospy.Publisher("sensor_summary", String, queue_size=10)
        rospy.Timer(rospy.Duration(1./float(self.hz)) self.summarize_data)

    def sensor_data_callback(self, msg):
        t = time()        
        self.history.append([t, msg.data])

    def summarize_data(self, event):
        if len(self.history) < 2:
            rospy.logwarn("Not enough data available to summarize.")
            return
        history = deepcopy(self.history)
        times = np.array([data[0] for data in history])
        avg_dt = np.mean(np.diff(times))  # Average time difference
        avg_hz = 1.0 / avg_dt if avg_dt > 0 else 0.0
        num_samples = len(history)
        sensor_data = "\n".join([str(data[1]) for data in history])        
        prompt = prompt_template.format(
            sensor_description=self.sensor_description,
            num_samples=num_samples,
            sensor_data=sensor_data,
            hz=avg_hz,
        )
        req = LLMRequest()
        req.prompt.data = prompt
        try:
            rospy.wait_for_service("call_llm", timeout=10.0)
            llm_service = rospy.ServiceProxy("call_llm", LLM)
            resp = llm_service(req)
            self.pub.publish(String(data=resp.response.response))            
        except Exception as e:
            rospy.logerr(f"Failed to summarize data: {e}")

    def spin(self):
        rospy.spin()

def main():
    GeneralSensorSummarizerNode().spin()    

if __name__ == "__main__":
    main()