#!/usr/bin/env python3
import rospy
import numpy as np
from copy import deepcopy
from time import time
from pathlib import Path
from collections import deque
from std_msgs.msg import Float64MultiArray, String

template = """# Sensor
{description}
The past {n} measurement{s}
{history}
"""

class TemplateSummarizerNode:
    def __init__(self):
        rospy.init_node("template_summarizer_node")
        self.max_history = rospy.get_param("~max_history", 1)
        self.history = deque(maxlen=self.max_history)
        self.sensor_description = Path(rospy.get_param("~sensor_description_path")).read_text()
        rospy.Subscriber("sensor_data", Float64MultiArray, self.sensor_data_callback)
        self.hz = rospy.get_param("~hz", 1.0)        
        self.pub = rospy.Publisher("sensor_summary", String, queue_size=10)
        rospy.Timer(rospy.Duration(1./float(self.hz)), self.summarize_data)

    def sensor_data_callback(self, msg):
        self.history.append(msg.data)

    def summarize_data(self, event):
        history = list(deepcopy(self.history))
        n = len(history)
        s = "s" if n > 1 else ""
        
        
        msg = String()
        msg.data = template.format(
            description=self.sensor_description,
            n=n,
            s=s,
            history=history,
        )

        self.pub.publish(msg)
        
    def spin(self):
        rospy.spin()

def main():
    TemplateSummarizerNode().spin()    

if __name__ == "__main__":
    main()
